# Generated by Django 5.0.6 on 2024-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_id', models.CharField(max_length=120)),
                ('start_power', models.FloatField()),
                ('end_power', models.FloatField()),
                ('start_water', models.FloatField()),
                ('end_water', models.FloatField()),
                ('createdAt', models.DateField()),
                ('date', models.DateField()),
                ('is_last_day_of_month', models.BooleanField()),
                ('is_first_day_of_month', models.BooleanField()),
                ('month', models.FloatField()),
                ('year', models.FloatField()),
                ('room_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('script', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperatureMax', models.FloatField()),
                ('windBearing', models.FloatField()),
                ('dewPoint', models.FloatField()),
                ('cloudCover', models.FloatField()),
                ('windSpeed', models.FloatField()),
                ('pressure', models.FloatField()),
                ('apparentTemperatureHigh', models.FloatField()),
                ('visibility', models.FloatField()),
                ('apparentTemperatureLow', models.FloatField()),
                ('apparentTemperatureMax', models.FloatField()),
                ('uvIndex', models.FloatField()),
                ('time', models.FloatField()),
                ('temperatureLow', models.FloatField()),
                ('temperatureMin', models.FloatField()),
                ('temperatureHigh', models.FloatField()),
                ('apparentTemperatureMin', models.FloatField()),
                ('moonPhase', models.FloatField()),
                ('clearday', models.FloatField()),
                ('cloudy', models.FloatField()),
                ('fog', models.FloatField()),
                ('partly_cloudy_day', models.FloatField()),
                ('partly_cloudy_night', models.FloatField()),
                ('wind', models.FloatField()),
                ('rain', models.FloatField()),
                ('snow', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='parent_endpoint',
        ),
        migrations.RemoveField(
            model_name='mlmodelstatus',
            name='parent_mlmodel',
        ),
        migrations.RemoveField(
            model_name='mlrequest',
            name='parent_mlmodel',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='MLModelStatus',
        ),
        migrations.DeleteModel(
            name='MLModel',
        ),
        migrations.DeleteModel(
            name='MLRequest',
        ),
    ]
